init:
  - git config --global core.autocrlf input

environment:
  matrix:
    - nodejs_version: 4.3.2

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install npm
  - .\node_modules\.bin\npm install


build: off

test_script:
  - node --version
  - .\node_modules\.bin\npm --version
  - .\node_modules\.bin\npm test
